<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit14a026996a92fad0c4fea02f01ccff7f
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('CheckoutWC\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \CheckoutWC\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit14a026996a92fad0c4fea02f01ccff7f', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \CheckoutWC\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit14a026996a92fad0c4fea02f01ccff7f', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\CheckoutWC\Composer\Autoload\ComposerStaticInit14a026996a92fad0c4fea02f01ccff7f::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \CheckoutWC\Composer\Autoload\ComposerStaticInit14a026996a92fad0c4fea02f01ccff7f::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
